<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>WinExe</OutputType>
		<TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>

		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>

		<PublishAot>true</PublishAot>
		<SelfContained>true</SelfContained>

		<StripSymbols>true</StripSymbols>

		<InvariantGlobalization>true</InvariantGlobalization>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<IncludeAllContentForSelfExtract>true</IncludeAllContentForSelfExtract>

		<BaseOutputPath>C:\AtomicShield\AtomicShieldClient\Build</BaseOutputPath>
		<ApplicationManifest>app.manifest</ApplicationManifest>
	</PropertyGroup>

	<Import Project="..\SharedLoader\SharedLoader.projitems" Label="Shared" />

</Project>
