<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows10.0.26100.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <PublishAot>true</PublishAot>
    <InvariantGlobalization>true</InvariantGlobalization>
    <AllowUnsafeBlocks>True</AllowUnsafeBlocks>
    <BaseOutputPath>C:\AtomicShield\AtomicShieldClient\Build</BaseOutputPath>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <PlatformTarget>x64</PlatformTarget>
  </PropertyGroup>

  <Import Project="..\SharedLoader\SharedLoader.projitems" Label="Shared" />

</Project>
