#pragma once

#define PROJECT_NAME "Atomic Shield"

#define VERSION_MAJOR "1"
#define VERSION_MINOR "1"

#define VERSION_BETA

#ifdef VERSION_BETA
    #define PROJECT_VERSION VERSION_MAJOR "." VERSION_MINOR "-b"
#else
    #define PROJECT_VERSION STRINGIFY(VERSION_MAJOR) "." STRINGIFY(VERSION_MINOR)
#endif

#define API_BASE_URL       "http://31.97.180.157"
#define WEBSOCKET_BASE_URL "ws://31.97.180.157:443"

#define CLIENT_BUILD_TIMESTAMP __TIMESTAMP__

#define STRINGIFY(x) #x
