#pragma once

enum eAtomicPacket
{
    NETWORK_JOIN = 1,
    SYNC_SIGNATURES,
    MALICIOUS_SIGNATURE,
    GAME_ANTICHEAT_COMPONENT_STATUS,
    CHEAT_DETECTION = 7,
    REQUEST_SCREENSHOT,
    RUN_SCANNERS,
    ENGINE_SHUTDOWN,
    REQUEST_DEBUG_LOGS,
    REQUEST_FILEHASH,
    REQUEST_FILE_UPLOAD,
    HEARTBEAT,
    FORCE_HARDKICK,
    RELOAD_ENGINE,
};